/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIS_H_RPCGEN
#define _DIS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXCOMMANDLEN 10
#define MAXFILENAME 20
#define MAXSTRLEN 1000
#define CAT "cat"
#define RM "rm"
#define LS "ls"
#define FIND "find"
#define WRITE "write"
#define CP "cp"
#define PWD "pwd"

typedef struct file *filelist;
#ifdef __cplusplus
extern "C" bool_t xdr_filelist(XDR *, filelist*);
#elif __STDC__
extern  bool_t xdr_filelist(XDR *, filelist*);
#else /* Old Style C */
bool_t xdr_filelist();
#endif /* Old Style C */

char key[120];

struct file {
	char *name;
	filelist next;
};
typedef struct file file;
#ifdef __cplusplus
extern "C" bool_t xdr_file(XDR *, file*);
#elif __STDC__
extern  bool_t xdr_file(XDR *, file*);
#else /* Old Style C */
bool_t xdr_file();
#endif /* Old Style C */


struct inparams {
	char *cmd;
	char *infile;
	int len;
	char *str;
};
typedef struct inparams inparams;
#ifdef __cplusplus
extern "C" bool_t xdr_inparams(XDR *, inparams*);
#elif __STDC__
extern  bool_t xdr_inparams(XDR *, inparams*);
#else /* Old Style C */
bool_t xdr_inparams();
#endif /* Old Style C */


struct outparams {
	long outfsize;
	char *outdata;
	struct file outlst;
	int errcode;
};
typedef struct outparams outparams;
#ifdef __cplusplus
extern "C" bool_t xdr_outparams(XDR *, outparams*);
#elif __STDC__
extern  bool_t xdr_outparams(XDR *, outparams*);
#else /* Old Style C */
bool_t xdr_outparams();
#endif /* Old Style C */


#define HWPROG ((rpc_uint)0x25510961)
#define HWVERS ((rpc_uint)1)

#ifdef __cplusplus
#define FILEPROG ((rpc_uint)1)
extern "C" outparams * fileprog_1(inparams *, CLIENT *);
extern "C" outparams * fileprog_1_svc(inparams *, struct svc_req *);

#elif __STDC__
#define FILEPROG ((rpc_uint)1)
extern  outparams * fileprog_1(inparams *, CLIENT *);
extern  outparams * fileprog_1_svc(inparams *, struct svc_req *);

#else /* Old Style C */
#define FILEPROG ((rpc_uint)1)
extern  outparams * fileprog_1();
extern  outparams * fileprog_1_svc();
#endif /* Old Style C */

#endif /* !_DIS_H_RPCGEN */
