/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dis.h"

bool_t
xdr_filelist(xdrs, objp)
	XDR *xdrs;
	filelist *objp;
{

	if (!xdr_pointer(xdrs, (char **)objp, sizeof(struct file), (xdrproc_t)xdr_file))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_file(xdrs, objp)
	XDR *xdrs;
	file *objp;
{

	if (!xdr_string(xdrs, &objp->name, MAXFILENAME))
		return (FALSE);
	if (!xdr_filelist(xdrs, &objp->next))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_inparams(xdrs, objp)
	XDR *xdrs;
	inparams *objp;
{

	if (!xdr_string(xdrs, &objp->cmd, MAXCOMMANDLEN))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->infile, MAXFILENAME))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->len))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->str, MAXSTRLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_outparams(xdrs, objp)
	XDR *xdrs;
	outparams *objp;
{

	if (!xdr_long(xdrs, &objp->outfsize))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->outdata, MAXSTRLEN))
		return (FALSE);
	if (!xdr_file(xdrs, &objp->outlst))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->errcode))
		return (FALSE);
	return (TRUE);
}
