/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dis.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

outparams *
fileprog_1(argp, clnt)
	inparams *argp;
	CLIENT *clnt;
{
	static outparams clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, FILEPROG, xdr_inparams, argp, xdr_outparams, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
